# Generated by Django 3.2.9 on 2022-02-09 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_set', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='nid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
