# Generated by Django 3.0.7 on 2022-03-16 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_set', '0003_auto_20220227_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='parcel',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True),
        ),
    ]
