# Generated by Django 3.0.7 on 2022-03-16 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_set', '0004_auto_20220316_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
