# Generated by Django 3.0.7 on 2022-03-16 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_set', '0005_auto_20220316_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
