# Generated by Django 3.0.7 on 2022-03-16 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_set', '0006_auto_20220316_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
