# Generated by Django 3.0.7 on 2022-03-30 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_set', '0008_auto_20220316_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='barcode',
            field=models.ImageField(blank=True, null=True, upload_to='barcode'),
        ),
    ]
