# Generated by Django 3.0.7 on 2022-04-11 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_set', '0009_parcel_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='cod_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='parcel',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
