# Generated by Django 3.0.7 on 2022-03-16 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='panda.jpg', upload_to='profile-pics'),
        ),
    ]
